import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  ReactDraw,
  circleTool,
  squareTool,
  selectTool,
  freeDrawTool,
  diamondTool,
  straightLineTool,
  textAreaTool,
  eraseTool,
  undoTool,
  redoTool,
  trashTool,
  duplicateTool,
  bringBackTool,
  bringForwardTool,
  ColorStyle,
  BackgroundStyle,
  LineWidthStyle,
  OpacityStyle,
  arrowTool,
  ClearAllButton,
  FontSizeStyle,
} from "@jzohdi/react-draw";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <ReactDraw
          id="main"
          topBarTools={[
            selectTool,
            freeDrawTool,
            squareTool,
            circleTool,
            diamondTool,
            straightLineTool,
            textAreaTool,
            arrowTool,
            eraseTool,
          ]}
          bottomBarTools={[
            undoTool,
            redoTool,
            trashTool,
            duplicateTool,
            bringBackTool,
            bringForwardTool,
          ]}
          shouldSelectAfterCreate={true}
          styleComponents={{
            color: { order: 3, component: ColorStyle },
            background: { order: 4, component: BackgroundStyle },
            lineWidth: { order: 1, component: LineWidthStyle },
            opacity: { order: 0, component: OpacityStyle },
            fontSize: { order: 2, component: FontSizeStyle },
          }}
          menuComponents={[ClearAllButton]}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
